# Generated by Django 3.0.1 on 2020-04-19 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=100, verbose_name='尺寸')),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=100, verbose_name='产地')),
            ],
        ),
        migrations.CreateModel(
            name='Kz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=100, verbose_name='克重')),
            ],
        ),
        migrations.CreateModel(
            name='Pm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm', models.CharField(max_length=100, verbose_name='品名')),
            ],
        ),
        migrations.CreateModel(
            name='Yh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yhh', models.CharField(max_length=6, verbose_name='用户号')),
                ('yhm', models.CharField(default='zlq', max_length=40, unique=True, verbose_name='用户名')),
                ('mm', models.CharField(max_length=10, verbose_name='密码')),
                ('scdl', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次登录时间')),
                ('yhlb', models.CharField(max_length=10, verbose_name='用户类别')),
            ],
        ),
        migrations.CreateModel(
            name='Dg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pe', models.CharField(choices=[('单PE', '单PE'), ('双PE', '双PE')], default='单PE', max_length=10)),
                ('xdrq', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('bz', models.CharField(max_length=200, verbose_name='备注')),
                ('jd', models.BooleanField(default='false', verbose_name='接单')),
                ('wd', models.BooleanField(default='false', verbose_name='完单')),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kst.Cc', verbose_name='尺寸')),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kst.Cd', verbose_name='产地')),
                ('kz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kst.Kz', verbose_name='克重')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kst.Pm', verbose_name='品名')),
                ('yhm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kst.Yh', to_field='yhm', verbose_name='订户名')),
            ],
        ),
    ]
