# Generated by Django 3.0.1 on 2020-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yh',
            name='yhm',
            field=models.CharField(default='用户名', max_length=40, unique=True, verbose_name='用户名'),
        ),
    ]
