# Generated by Django 3.0.1 on 2020-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0002_auto_20200419_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yh',
            name='yhlb',
            field=models.CharField(choices=[('客户', '客户'), ('操作', '操作'), ('管理', '管理')], max_length=10, verbose_name='用户类别'),
        ),
    ]
