# Generated by Django 3.0.1 on 2020-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0004_auto_20200426_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dg',
            name='cc',
            field=models.CharField(max_length=100, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='dg',
            name='cd',
            field=models.CharField(max_length=100, verbose_name='产地'),
        ),
        migrations.AlterField(
            model_name='dg',
            name='kz',
            field=models.CharField(max_length=100, verbose_name='克重'),
        ),
    ]
