# Generated by Django 3.0.1 on 2020-04-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0005_auto_20200426_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cc',
        ),
        migrations.DeleteModel(
            name='Cd',
        ),
        migrations.DeleteModel(
            name='Kz',
        ),
        migrations.DeleteModel(
            name='Pm',
        ),
    ]
