# Generated by Django 3.0.1 on 2020-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0006_auto_20200426_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dg',
            name='yhm',
            field=models.CharField(max_length=100, verbose_name='订户名'),
        ),
    ]
