# Generated by Django 3.0.1 on 2020-05-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0007_auto_20200426_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='dg',
            name='yhrq',
            field=models.CharField(default='', max_length=20, verbose_name='要货日期'),
        ),
        migrations.AlterField(
            model_name='yh',
            name='yhlb',
            field=models.CharField(max_length=10, verbose_name='用户类别'),
        ),
    ]
